singular: fix parallel make.
Encountered an error message like this:
Assembler messages:
Fatal error: can't create OPTOBJ/SqrFree.o: No such file or directory
Assembler messages:
Fatal error: can't create OPTOBJ/Factor.o: No such file or directory
make[2]: *** [OPTOBJ/SqrFree.o] Error 2
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [OPTOBJ/Factor.o] Error 2
make[2]: Leaving directory `/var/tmp/portage/sci-mathematics/singular-3.1.1.4-r1/work/Singular-3-1-1/libfac'
make[1]: *** [install] Error 1
make[1]: Leaving directory `/var/tmp/portage/sci-mathematics/singular-3.1.1.4-r1/work/Singular-3-1-1'
make: *** [/var/tmp/portage/sci-mathematics/singular-3.1.1.4-r1/work/Singular-3-1-1/build/bin/Singular-3-1-1] Error 2
emake failed

It seems that due to parallel build, one rule tried creating these targets
before the rule responsible for the creation of the containing dir was
completed or even started.

The old patch didn't really fix the issue. In order to guarantee for OPTOBJ
to be actually present even in parallel builds before some rule tries to
place a target in there, there are basically two options: either
a) have every such target depend on OPTOBJ or
b) ensure that OPTOBJ gets executed before make gets invoked for the targets
   that need it.

Alternative a) has the drawback that every target would depend not only on
the existence of the directory, but on its timestamp as well.  For Gentoo
that wouldn't be too much of a problem, but in general it might cause a lot
of unnecessary rebuilds during development, making the patch fairly
unsuitable for upstream inclusion.  So we go for alternative b) and have the
all target ensure that OPTOBJ exists (via dependency) before it goes for the
other targets (via recursive call in the rule).  The target install depends
on all and therefore should already be fixed by this patch as well.